---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : brandon
production_url : http://cyounes.com

posts:
  permalink: /:categories/:title
  summary_lines: 0
  latest: 4

pages:
  permalink: 'pretty'

