title : cYounes
tagline: Personal website
author :
  name : Cheikh Younes
  email : younes.cheikh@gmail.com
  github : cyounes
  twitter : cyounes
  feedburner : cyounes

navigation :
  - projects/index.md
  - about.md
  - archive.html
  
